on: 
  push:
    branches:
      - main
name: Build and Publish
env:
  NODE_VERSION: 16.x

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        registry-url: https://registry.npmjs.org/
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{env.NODE_VERSION}}-${{runner.OS}}-build-${{hashFiles('package.json')}}
    - name: Build
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install
    - name: Automated Version Bump
      uses: phips28/gh-action-bump-version@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        commit-message: 'CI: bump version to {{version}}'
    - name: Publish NPM package
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      run:
        npm publish
